#!/bin/bash

# This script tests multiple packages and creates a consolidated cover profile
# See https://gist.github.com/hailiang/0f22736320abe6be71ce for inspiration.
# The list of packages to test is specified in testpackages.txt.

function die() {
  echo $*
  exit 1
}

export GOPATH=`pwd`:$GOPATH

# Initialize profile.cov
echo "mode: count" > profile.cov

# Initialize error tracking
ERROR=""

PKGS=""
for arg in $@; do # pass multiple packages on command line
  for godir in $(tr : "\n"<<<$GOPATH); do # Find them anywhere in GOPATH
    for found in $(find $godir/src/$arg -type d); do # Listing all valid directories
      dir=$(sed "s*${godir}/src/**" <<< $found) # And representing them as package names
      if [ "${dir}" != "./vendor/" -a "${dir}" != "./protos/" ]; then # skipping some vendered stuff
        PKGS="${PKGS} ${dir}..."
      fi
    done
  done
done
echo $PKGS

# Test each package and append coverage profile info to profile.cov
for pkg in $PKGS; do
    #echo testing $pkg with coverage
    #$HOME/gopath/bin/
    echo '' > profile_tmp.cov
    go test -v -covermode=count -coverprofile=profile_tmp.cov $pkg || ERROR="Error testing $pkg"
    tail -n +2 profile_tmp.cov >> profile.cov || die "Unable to append coverage for $pkg"
done

if [ ! -z "$ERROR" ]
then
    die "Encountered error, last error was: $ERROR"
fi

echo Opening coverage as html
go tool cover -html=profile.cov

#- GOPATH=`pwd`:$GOPATH $HOME/gopath/bin/goveralls -v -service travis-ci github.com/getlantern/buuid
